"""
Pipeline for Allele Specific Expression estimation
"""
import os

configfile: "config/config.yaml"

# Import sample config (sample name, sra accession)
import pandas as pd

samples = (
    pd.read_csv(config["samples"], sep="\t", dtype={"sample_name": str, "sra": str})
    .set_index("sample_name", drop=False)
    .sort_index()
)

sample = samples["sample_name"]
sra = samples["sra"]

# Only accepts a single genome
genome = config["genome"]
prefix = config["prefix"]

wdir = config['datadir'] + prefix

wildcard_constraints:
    wdir = wdir,
    genome = genome,
    prefix = prefix


include: "common.smk"
include: "rules/common.smk"
include: "rules/data_download.smk"

rule all:
    input:
        expand("{wdir}/fastq/{sra}_1.fastq.gz", wdir=wdir, sra=sra),
        expand("{wdir}/fastq/{sra}_2.fastq.gz", wdir=wdir, sra=sra),
        expand("{wdir}/genome/{genome}.fna", wdir=wdir, genome=genome)

