executor: slurm
use-conda: True
jobs: 25 # Have up to N jobs submitted at any given time
latency-wait: 100 # Wait N seconds for output files due to latency
retries: 0 # Retry jobs N times.

# These resources will be applied to all rules. Can be overriden on a per-rule basis below.
default-resources:
  mem_mb: attempt * 2000
  mem_mb_reduced: (attempt * 2000) * 0.9 # Reduced mem allocated to prevent OOM errors
  cpus_per_task: 1
  slurm_partition: "genouest,ecobio"
  slurm_account: "tbrazier" # Same as sbatch -A. Not all clusters use this.
  runtime: 2880 # In minutes


# Control number of threads each rule will use.
set-threads:
  # Reference Genome Processing. Does NOT use more than 1 thread.
  download_sra_rnaseq: 1
  download_genome: 1
 
# Control other resources used by each rule.
set-resources:
#   download_sra_rnaseq:
#     mem_mb: attempt * 2000
#     slurm_partition:
#     runtime:
#     cpus_per_task:
#   download_genome:
#     mem_mb: attempt * 2000
#     slurm_partition:
#     runtime:
#     cpus_per_task:
